### ISSUE TITLE
Corruption in Pipermail Files | Special Character Preservation

### ISSUE THREAD

**Issue by nyghtowl** [google/project-OCEAN#13]
## Expected Behavior
Preserve special characters. 

## Actual Behavior
Appears that the files didn't fully preserve special characters. Files may just be ascii, using literal '?'s for non-ascii chars. Need further investigation to determine how much this is an issue and how to resolve.

Example

One file I'm using as a check is pipermail-python-list-gzip/2011-February.txt.gz ...If you search for the name "Westley" in that file, you'll see lines like "Westley Mart?nez wrote:" , with (apparently) a literal "?". (the header lines in the file like: "From: anikom15 at gmail.com (Westley =?ISO-8859-1?Q?Mart=EDnez?=)" are treated differently -- those are decodable)

Investigation confirmed that these malformations are in the original zipped files that were on the site.

## Steps to Reproduce the Problem

1.
1.
1.

## Specifications

- Version:
- Platform:

**Comment by glasnt** [comment]
Closing, see #97
