### ISSUE TITLE
Improve To parsing in the mailing list data that is loaded to BQ

### ISSUE THREAD

**Issue by nyghtowl** [google/project-OCEAN#42]
## Expected Behavior

Mailing list To field should be populated by the target person that the email is responding to. 

## Actual Behavior

In python_mailinglist table there are some messages where To is showing up in the body but not populating the To field.

Body: "B Zy < zy at gmail.com> wrote: 
> Hello 
> Help my code."

The To field is capturing the mailing list name instead. 

## Steps to Reproduce the Problem

1. Review python mailing list examples
1. Improve parsing in the extract_msgs script, probably a regex for the body
1.

**Comment by nyghtowl** [comment]
Found To is still not fully parsing when everything was reloaded into BigQuery. Code and test needs to be reviewed based on actual data in BQ to see what the disconnect is.

**Comment by glasnt** [comment]
Closing, see #97
