### ISSUE TITLE
Add original content url to pipermail and mailman data

### ISSUE THREAD

**Issue by nyghtowl** [google/project-OCEAN#45]
## Expected Behavior

Pull out url where the data originated from for pipermail and mailman and put in BQ

## Actual Behavior

Currently the urls used to get the data are not stored and  this would be good for reference

## Ideas for how to fix

- Include the url in the filename (the syntax is an issue)
- Open files and append url on the end

**Comment by glasnt** [comment]
Closing, see https://github.com/google/project-OCEAN/issues/97
