### ISSUE TITLE
Update README in 2-transform-data

### ISSUE THREAD

**Issue by nyghtowl** [google/project-OCEAN#50]
Readme is out of date and needs clean up to align to current state. For example its no longer in review segment. The code works and has been merged.

https://github.com/google/project-OCEAN/blob/master/2-transform-data/manual_bq_ingest/README.md

**Comment by tymsai** [comment]
2-transform-data has no readme.
can you provide a link for your above statement.

**Comment by nyghtowl** [comment]
Its in the manual folder. Link added

**Comment by glasnt** [comment]
Closing, see #97
