### ISSUE TITLE
Python test for BigQuery load

### ISSUE THREAD

**Issue by nyghtowl** [google/project-OCEAN#52]
In extract_mgs_test.py, add test for the function store_in_bigquery

**Comment by frankyan1119** [comment]
I am new to open source projects, and I would like to start working on this.

**Comment by nyghtowl** [comment]
Welcome and please go forth and have fun.

**Comment by frankyan1119** [comment]
Hi Melanie @nyghtowl 

For some reason **client.insert_rows_json(table, json_row)** keeps returning this error:

**"This json row did not load to BigQuery: [........] and threw this error: <MagicMock name='Client().insert_rows_json()' id='186397528'>"**

I have created a mock client:

    @mock.patch("google.cloud.storage.Client")
    def create_client_mock(self, Client):
        client = Client()

        with open("table_schema.json") as f:
            schema = json.load(f)
        table_framework = em.bigquery.Table("some_project.some_dataset.1", schema=schema)
        client.create_table(table_framework)

        return client

Am I missing anything?

**Comment by nyghtowl** [comment]
Hi Yahao - Can you submit a draft PR with the current state of the code? It will be easier to pull and review to respond. And let me know if you need any info for submitting a PR.

**Comment by nyghtowl** [comment]
Looking at the code snippet you shared, the mock.patch stands out as something that needs adjustment to focus on bigquery vs storage.

Look at line 253 / create_bucket_mock for ideas on approach but see if you can swap with something like: https://googleapis.dev/python/bigquery/latest/_modules/google/cloud/bigquery/client.html

I don't have a confirmation this is exactly the thing to use but seems the right direciton.

**Comment by frankyan1119** [comment]
Sorry, I need more time to look into this. 

So I will leave this issue open for others for now.

**Comment by nyghtowl** [comment]
Thanks for the contribution. Definitely appreciated. I made some recommendations directly into the PR if you get bandwith.

**Comment by glasnt** [comment]
Closing, see #97
